name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [assigned]

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  claude-response:
    if: |
      (
        contains(github.event.comment.body, '@claude') ||
        contains(github.event.issue.body, '@claude') ||
        contains(github.event.pull_request.body, '@claude')
      ) &&
      !github.event.issue.pull_request &&
      github.event.sender.type != 'Bot'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Optional configurations:
          # model: claude-3-5-sonnet-20241022  # Default model
          # max_turns: 10  # Maximum conversation turns
          # trigger_phrase: "@claude"  # Custom trigger phrase
          # allowed_tools: "bash,github,mcp"  # Enable specific tools
